### ISSUE TITLE
Running without Docker

### ISSUE THREAD

**Issue by ainhoaarnaiz** [inorbit-ai/vda5050_adapter_examples#10]
Hi, 

I have tried to run it without Docker, but this is the output I get:

![Screenshot from 2023-03-22 12-47-55](https://user-images.githubusercontent.com/128591235/226882666-4d63c3ed-62a1-4f11-94c0-bb55415139ff.png)
![Screenshot from 2023-03-22 12-59-11](https://user-images.githubusercontent.com/128591235/226883538-036b6e28-270f-4797-9138-1689eaa45ffd.png)
![Screenshot from 2023-03-22 12-48-30](https://user-images.githubusercontent.com/128591235/226883715-94276ebb-8dc3-4681-bb00-a899ec56a079.png)
![Screenshot from 2023-03-22 12-51-14](https://user-images.githubusercontent.com/128591235/226883734-97cc0d2f-4985-4ffe-ac4c-fcc12944ea3b.png)

The topics are getting published on ROS2 but not on MQTT. Apparently, **is not connecting to the MQTT broker.**

**Steps to follow:**
Ubuntu 22.04
ROS2 Humble

**Packages in workspace:**
![Screenshot from 2023-03-22 12-52-11](https://user-images.githubusercontent.com/128591235/226883915-9713c33f-a1c9-4499-a765-c632d7b847c5.png)

**Execution:**
- Start Mosquitto broker with Docker (T1): `docker run --rm --network host --name mosquitto eclipse-mosquitto`
- Launch TurtleBot 3 simulation (T2): 
	`export TURTLEBOT3_MODEL=waffle`
	`export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models`
	`export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`
	`ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False`

I manually set the initial pose of the TurtleBot 3

![Screenshot from 2023-03-22 12-49-34](https://user-images.githubusercontent.com/128591235/226885650-55f79128-7d37-4a30-a64d-75914c8e5156.png)
![Screenshot from 2023-03-22 12-49-41](https://user-images.githubusercontent.com/128591235/226885717-e9e7e500-755c-48cf-be20-5623b70573b0.png)

- Launch connector tb3 (T3): `ros2 launch vda5050_tb3_adapter connector_tb3.launch.py`

However, if I just run: `ros2 launch vda5050_connector mqtt_bridge.launch.py`, this happens:

![Screenshot from 2023-03-22 12-53-14](https://user-images.githubusercontent.com/128591235/226885119-a81e1772-0735-47a0-9df7-6cd9c2f14790.png)
![Screenshot from 2023-03-22 13-08-55](https://user-images.githubusercontent.com/128591235/226886793-4e147091-b215-48ae-8647-b49c57b5dd2a.png)

Any clue? Thank you very much!

**Comment by leandropineda** [comment]
Hi!

I think it's just a configuration issue. The example is docker based so by default it will try to reach the MQTT broker by using `mosquitto` hostname instead of `localhost`: https://github.com/inorbit-ai/vda5050_adapter_examples/blob/galactic-devel/vda5050_tb3_adapter/config/connector_tb3.yaml#L3.

When you launch it from the `mqtt_bridge` launch file it uses `localhost` instead: https://github.com/inorbit-ai/ros_amr_interop/blob/humble-devel/vda5050_connector/config/connector_example.yaml#L3.

**Comment by ainhoaarnaiz** [comment]
Hi!
Thank you, that worked perfectly!
