### ISSUE TITLE
initPosition VDA Action not finishing

### ISSUE THREAD

**Issue by fmros** [inorbit-ai/vda5050_adapter_examples#5]
Hy!

When calling the **initPosition** actionType as e.g. indicated in in [this](https://github.com/inorbit-ai/vda5050_adapter_examples/tree/galactic-devel/vda5050_tb3_adapter#readme) ReadMe, the action seems to never switch its state to finish. 

I had a look at the [tb3_adapter.py](https://github.com/inorbit-ai/vda5050_adapter_examples/blob/galactic-devel/vda5050_tb3_adapter/vda5050_tb3_adapter/tb3_adapter.py) and found that most probably the block of code from [here](https://github.com/inorbit-ai/vda5050_adapter_examples/blob/e074d434491e20897f3b5e736416f44e8cf9e2a2/vda5050_tb3_adapter/vda5050_tb3_adapter/tb3_adapter.py#L224) to [here](https://github.com/inorbit-ai/vda5050_adapter_examples/blob/e074d434491e20897f3b5e736416f44e8cf9e2a2/vda5050_tb3_adapter/vda5050_tb3_adapter/tb3_adapter.py#L244) should not be part of the `else` scope. When shifting it outward, the action returns after some seconds with follwoing output:
```
[vda5050_controller.py-2] [INFO] [1668002862.962848970] [vda5050_connector.controller]: VDA Action finished. Result: vda5050_msgs.msg.CurrentAction(action_id='add9173d-9546-47b7-8cdf-77badd3fa1bf', action_description='', action_status='FINISHED', result_description='')
```

**Comment by leandropineda** [comment]
I was able to reproduce the issue. Removing the `else` block as you tried does report the action as finished but also executes the "dummy" action the adapter runs when issued with an unsupported instant action. I have created a PR with the fix. Can you confirm that it does solve the issue?

**Comment by fmros** [comment]
i tried your PR and it works as expected! Thanks..
